
export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";


